import type { Card } from '@engine/types';

// The Kaurava host and its allies at Kurukshetra. Top-tier maharathis shielded
// by canonical boons and curses, the Bahlika elders, allied kings, and the
// rakshasa night-fighters. Tags drive bond/synergy.
export const KAURAVA_CARDS: Card[] = [
  // ---- The four commanders ----
  {
    id: 'bhishma',
    name: 'Bhishma',
    house: 'kaurava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 10,
    rows: ['ratha'],
    keywords: [{ kind: 'icchamrityu', unlessCardOnBoard: 'shikhandi' }],
    effects: [],
    astraMastery: 2,
    flavor: 'Granted the boon to choose the hour of his own death.',
  },
  {
    id: 'drona',
    name: 'Drona',
    house: 'kaurava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 9,
    rows: ['ratha'],
    keywords: [{ kind: 'immuneUntilPlayed', card: 'ashwatthama_elephant', thenSetPower: 0 }],
    effects: [],
    astraMastery: 2,
    knownAstras: ['brahmashirsha'],
    flavor: 'The war-guru, unbeatable until grief unstrung his bow.',
  },
  {
    id: 'karna',
    name: 'Karna',
    house: 'kaurava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 10,
    rows: ['ratha'],
    keywords: [{ kind: 'armor', amount: 4 }, { kind: 'noAstrasInFinalRound' }],
    tags: ['sun-line'],
    astraMastery: 2,
    knownAstras: ['vasavi_shakti'],
    effects: [
      {
        on: 'onPlay',
        condition: { q: 'isFinalRound' },
        target: { pick: 'self' },
        actions: [{ kind: 'setPower', value: 0 }, { kind: 'addFlag', flag: 'wheel-sunk' }],
      },
    ],
    flavor: 'Son of the Sun, undone by two curses at the last.',
  },
  {
    id: 'shalya',
    name: 'Shalya',
    house: 'kaurava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 8,
    rows: ['ratha'],
    keywords: [],
    // The poison tongue: fielding Shalya saps your own Karna (his secret sabotage).
    effects: [
      {
        on: 'onPlay',
        target: { pick: 'unitByCard', side: 'own', card: 'karna' },
        actions: [{ kind: 'buff', amount: -3 }],
      },
    ],
    flavor: 'The Madra king who steered Karna’s chariot and his ruin.',
  },

  // ---- The Kuru princes ----
  {
    id: 'duryodhana',
    name: 'Duryodhana',
    house: 'kaurava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 9,
    rows: ['ratha'],
    keywords: [],
    tags: ['kaurava-brother'],
    effects: [{ on: 'onPlay', target: { pick: 'self' }, actions: [{ kind: 'addFlag', flag: 'diamond-body' }] }],
    flavor: 'Adamantine but for the thighs his mother never saw.',
  },
  {
    id: 'dushasana',
    name: 'Dushasana',
    house: 'kaurava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 6,
    rows: ['ratha', 'gaja'],
    keywords: [],
    tags: ['kaurava-brother'],
    effects: [],
    flavor: 'Whose hands at the dice-hall sealed the war.',
  },
  {
    id: 'vikarna',
    name: 'Vikarna',
    house: 'kaurava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [],
    tags: ['kaurava-brother'],
    effects: [],
    flavor: 'The only brother who named the wrong a wrong.',
  },
  {
    id: 'chitrasena',
    name: 'Chitrasena',
    house: 'kaurava',
    type: 'unit',
    tier: 'rathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'kaurava-brother', amount: 1 }],
    tags: ['kaurava-brother'],
    effects: [],
    flavor: 'One of the hundred, cut down in Bhima’s vow.',
  },
  {
    id: 'vivimsati',
    name: 'Vivimsati',
    house: 'kaurava',
    type: 'unit',
    tier: 'rathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'kaurava-brother', amount: 1 }],
    tags: ['kaurava-brother'],
    effects: [],
    flavor: 'A steadier hand than most of his hundred brothers.',
  },
  {
    id: 'durmukha',
    name: 'Durmukha',
    house: 'kaurava',
    type: 'unit',
    tier: 'rathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'kaurava-brother', amount: 1 }],
    tags: ['kaurava-brother'],
    effects: [],
    flavor: 'Fierce of face, as his name is read.',
  },

  // ---- The inner circle (gurus and kin) ----
  {
    id: 'ashwatthama',
    name: 'Ashwatthama',
    house: 'kaurava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 8,
    rows: ['ratha'],
    keywords: [{ kind: 'deathless' }],
    astraMastery: 2,
    knownAstras: ['narayanastra', 'brahmashirsha'],
    effects: [],
    flavor: 'Drona’s son, cursed to wander deathless and unhealing.',
  },
  {
    id: 'kripa',
    name: 'Kripa',
    house: 'kaurava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 7,
    rows: ['ratha'],
    keywords: [{ kind: 'deathless' }],
    astraMastery: 2,
    effects: [],
    flavor: 'The deathless teacher who outlived the war he fought.',
  },
  {
    id: 'kritavarma',
    name: 'Kritavarma',
    house: 'kaurava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 7,
    rows: ['ratha'],
    keywords: [{ kind: 'nightGrowth', amount: 2 }],
    tags: ['vrishni'],
    effects: [],
    flavor: 'The Yadava who took the army, not the god.',
  },
  {
    id: 'shakuni',
    name: 'Shakuni',
    house: 'kaurava',
    type: 'unit',
    tier: 'rathi',
    basePower: 3,
    rows: ['padati'],
    keywords: [],
    effects: [{ on: 'onPlay', target: { pick: 'highestEnemyUnit' }, actions: [{ kind: 'damage', amount: 3 }] }],
    flavor: 'His dice never rolled true for anyone but him.',
  },
  {
    id: 'uluka',
    name: 'Uluka',
    house: 'kaurava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [],
    effects: [],
    flavor: 'He carried the message that made peace impossible.',
  },

  // ---- The Bahlika line ----
  {
    id: 'bahlika',
    name: 'Bahlika',
    house: 'kaurava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 6,
    rows: ['ratha'],
    keywords: [],
    effects: [],
    flavor: 'An elder of Shantanu’s own blood, fighting past his years.',
  },
  {
    id: 'somadatta',
    name: 'Somadatta',
    house: 'kaurava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 6,
    rows: ['ratha'],
    keywords: [],
    effects: [],
    flavor: 'Heir of Bahlika, marked by an ancient feud.',
  },
  {
    id: 'bhurishravas',
    name: 'Bhurishravas',
    house: 'kaurava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 8,
    rows: ['ratha'],
    keywords: [],
    effects: [],
    flavor: 'He laid down arms to die in prayer, and was struck down at it.',
  },

  // ---- Allied kings ----
  {
    id: 'jayadratha',
    name: 'Jayadratha',
    house: 'kaurava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 6,
    rows: ['ratha'],
    keywords: [],
    effects: [
      {
        on: 'onPlay',
        target: { pick: 'none' },
        actions: [{ kind: 'debuffRow', amount: -2, rows: [{ side: 'enemy', row: 'padati' }], duration: 'round' }],
      },
    ],
    flavor: 'The gate-keeper who sealed Abhimanyu inside the wheel.',
  },
  {
    id: 'bhagadatta',
    name: 'Bhagadatta',
    house: 'kaurava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 8,
    rows: ['gaja'],
    keywords: [],
    astraMastery: 1,
    knownAstras: ['vaishnavastra'],
    effects: [{ on: 'onPlay', target: { pick: 'highestEnemyUnit' }, actions: [{ kind: 'damage', amount: 2 }] }],
    flavor: 'The aged lord of Pragjyotisha, astride the great elephant Supratika.',
  },
  {
    id: 'vinda',
    name: 'Vinda',
    house: 'kaurava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'avanti', amount: 2 }],
    tags: ['avanti'],
    effects: [],
    flavor: 'One half of the Avanti brothers, never seen apart.',
  },
  {
    id: 'anuvinda',
    name: 'Anuvinda',
    house: 'kaurava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'avanti', amount: 2 }],
    tags: ['avanti'],
    effects: [],
    flavor: 'The other half of the Avanti brothers.',
  },
  {
    id: 'susharma',
    name: 'Susharma',
    house: 'kaurava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 6,
    rows: ['ratha'],
    keywords: [],
    tags: ['samshaptaka'],
    effects: [],
    flavor: 'He swore to kill Arjuna or never leave the field.',
  },
  {
    id: 'sudakshina',
    name: 'Sudakshina',
    house: 'kaurava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 6,
    rows: ['ratha'],
    keywords: [],
    effects: [],
    flavor: 'The Kamboja king and his tide of northern horse.',
  },
  {
    id: 'srutayudha',
    name: 'Srutayudha',
    house: 'kaurava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 6,
    rows: ['ratha'],
    keywords: [],
    effects: [],
    flavor: 'His own boon-mace turned back and slew him.',
  },
  {
    id: 'jalasandha',
    name: 'Jalasandha',
    house: 'kaurava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 6,
    rows: ['gaja'],
    keywords: [],
    effects: [],
    flavor: 'The Magadha lord who rode into Satyaki’s path.',
  },

  // ---- The rakshasa night-fighters ----
  {
    id: 'alambusha',
    name: 'Alambusha',
    house: 'kaurava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 6,
    rows: ['ratha'],
    keywords: [{ kind: 'nightGrowth', amount: 2 }, { kind: 'bond', tag: 'rakshasa', amount: 1 }],
    tags: ['rakshasa'],
    effects: [],
    flavor: 'The night-demon who killed Arjuna’s serpent-son.',
  },
  {
    id: 'alayudha',
    name: 'Alayudha',
    house: 'kaurava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 7,
    rows: ['gaja'],
    keywords: [{ kind: 'nightGrowth', amount: 3 }, { kind: 'bond', tag: 'rakshasa', amount: 1 }],
    tags: ['rakshasa'],
    effects: [],
    flavor: 'He came to avenge his kin, and lost his head to Bhima’s son.',
  },

  // ---- Karna's house ----
  {
    id: 'vrishasena',
    name: 'Vrishasena',
    house: 'kaurava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 7,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'sun-line', amount: 2 }],
    tags: ['sun-line'],
    effects: [],
    flavor: 'The Sun-son’s son, cut down before his father’s eyes.',
  },

  // ---- Levy ----
  {
    id: 'kaurava_infantry',
    name: 'Kaurava Footmen',
    house: 'kaurava',
    type: 'unit',
    tier: 'rathi',
    basePower: 2,
    rows: ['padati'],
    keywords: [],
    effects: [],
    flavor: 'Eleven akshauhinis marched for Hastinapura.',
  },
];
