import type { Card } from '@engine/types';

// The Pandava host and its allies at Kurukshetra. Base powers map to the canon
// rathi/atirathi/maharathi ranking. Tags drive bond/synergy.
export const PANDAVA_CARDS: Card[] = [
  // ---- The five Pandavas ----
  {
    id: 'arjuna',
    name: 'Arjuna',
    house: 'pandava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 10,
    rows: ['ratha'],
    keywords: [],
    effects: [],
    tags: ['pandava-brother'],
    knownAstras: [
      'brahmastra',
      'brahmashirsha',
      'agneyastra',
      'varunastra',
      'aindrastra',
      'sammohana',
      'vayavyastra',
      'garudastra',
      'pashupatastra',
    ],
    flavor: 'The finest archer of the age, wielder of the Gandiva.',
  },
  {
    id: 'bhima',
    name: 'Bhima',
    house: 'pandava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 9,
    rows: ['ratha', 'gaja'],
    keywords: [],
    tags: ['pandava-brother'],
    effects: [
      {
        on: 'onPlay',
        target: { pick: 'chosen', filter: { side: 'enemy' } },
        condition: { q: 'targetHasFlag', flag: 'diamond-body' },
        actions: [{ kind: 'removeFlag', flag: 'diamond-body' }, { kind: 'destroy' }],
      },
    ],
    flavor: 'His mace-vow: to break the thigh of Duryodhana.',
  },
  {
    id: 'yudhishthira',
    name: 'Yudhishthira',
    house: 'pandava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 7,
    rows: ['ratha'],
    keywords: [],
    tags: ['pandava-brother'],
    effects: [
      {
        on: 'onPlay',
        target: { pick: 'none' },
        actions: [{ kind: 'debuffRow', amount: 2, rows: [{ side: 'own', row: 'padati' }], duration: 'round' }],
      },
    ],
    flavor: 'The king of righteousness, whose one lie felled Drona.',
  },
  {
    id: 'nakula',
    name: 'Nakula',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 6,
    rows: ['ratha', 'padati'],
    keywords: [{ kind: 'bond', tag: 'twin', amount: 2 }],
    tags: ['pandava-brother', 'twin'],
    effects: [],
    flavor: 'Twin of the Ashvins, matchless with the sword.',
  },
  {
    id: 'sahadeva',
    name: 'Sahadeva',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 6,
    rows: ['ratha', 'padati'],
    keywords: [{ kind: 'bond', tag: 'twin', amount: 2 }],
    tags: ['pandava-brother', 'twin'],
    // Sworn to kill Shakuni: cuts down the dice-master on sight.
    effects: [
      {
        on: 'onPlay',
        target: { pick: 'unitByCard', side: 'enemy', card: 'shakuni' },
        actions: [{ kind: 'destroy' }],
      },
    ],
    flavor: 'The wisest of the five, who knew what was to come.',
  },

  // ---- Krishna (does not fight) ----
  {
    id: 'krishna_charioteer',
    name: 'Krishna, the Charioteer',
    house: 'pandava',
    type: 'boon',
    basePower: 0,
    provision: 10,
    rows: ['ratha'],
    keywords: [],
    effects: [
      {
        on: 'onPlay',
        target: { pick: 'chosen', filter: { side: 'own', rows: ['ratha'] } },
        actions: [{ kind: 'buff', amount: 3 }, { kind: 'addFlag', flag: 'krishna-guarded' }],
      },
    ],
    flavor: 'He would not fight, he would only drive, and counsel.',
  },

  // ---- Divine-born and next-generation sons ----
  {
    id: 'abhimanyu',
    name: 'Abhimanyu',
    house: 'pandava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 8,
    rows: ['ratha'],
    keywords: [],
    knownAstras: ['brahmastra'],
    effects: [
      {
        on: 'onRoundEnd',
        condition: { q: 'cardOnBoard', card: 'jayadratha', side: 'enemy' },
        target: { pick: 'self' },
        actions: [{ kind: 'destroy' }],
      },
    ],
    flavor: 'Sixteen, and alone inside the wheel formation.',
  },
  {
    id: 'ghatotkacha',
    name: 'Ghatotkacha',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 7,
    rows: ['gaja'],
    keywords: [{ kind: 'nightGrowth', amount: 3 }],
    tags: ['rakshasa'],
    effects: [],
    flavor: 'The rakshasa son of Bhima, who waxes as the night deepens.',
  },
  {
    id: 'iravan',
    name: 'Iravan',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 6,
    rows: ['ratha'],
    keywords: [],
    tags: ['naga'],
    effects: [],
    flavor: 'Ulupi’s serpent-son, who fought the sky itself before he fell.',
  },
  {
    id: 'anjanaparvan',
    name: 'Anjanaparvan',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 5,
    rows: ['gaja'],
    keywords: [{ kind: 'nightGrowth', amount: 2 }, { kind: 'bond', tag: 'rakshasa', amount: 2 }],
    tags: ['rakshasa'],
    effects: [],
    flavor: 'Ghatotkacha’s son, and Ashwatthama’s kill.',
  },

  // The five Upapandavas (sons of Draupadi), a bonded line
  {
    id: 'prativindhya',
    name: 'Prativindhya',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'upapandava', amount: 1 }],
    tags: ['upapandava'],
    effects: [],
    flavor: 'Eldest of the five princes, son of Yudhishthira.',
  },
  {
    id: 'sutasoma',
    name: 'Sutasoma',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'upapandava', amount: 1 }],
    tags: ['upapandava'],
    effects: [],
    flavor: 'Son of Bhima, of the fire-born queen’s line.',
  },
  {
    id: 'shrutakarma',
    name: 'Shrutakarma',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'upapandava', amount: 1 }],
    tags: ['upapandava'],
    effects: [],
    flavor: 'Son of Arjuna, cut down asleep.',
  },
  {
    id: 'shatanika',
    name: 'Shatanika',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'upapandava', amount: 1 }],
    tags: ['upapandava'],
    effects: [],
    flavor: 'Son of Nakula, of the unbroken line.',
  },
  {
    id: 'shrutasena',
    name: 'Shrutasena',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'upapandava', amount: 1 }],
    tags: ['upapandava'],
    effects: [],
    flavor: 'Youngest son of Sahadeva.',
  },

  // ---- Panchala (Draupadi's house) ----
  {
    id: 'dhrishtadyumna',
    name: 'Dhrishtadyumna',
    house: 'pandava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 8,
    rows: ['ratha'],
    keywords: [],
    tags: ['panchala'],
    knownAstras: ['agneyastra', 'brahmastra'],
    // Born to slay Drona: strikes him down once he has laid down his bow
    // (Drona's immunity holds until the "Ashwatthama is dead" deception disarms him).
    effects: [
      {
        on: 'onPlay',
        target: { pick: 'unitByCard', side: 'enemy', card: 'drona' },
        actions: [{ kind: 'destroy' }],
      },
    ],
    flavor: 'Born of fire to be the slayer of Drona.',
  },
  {
    id: 'shikhandi',
    name: 'Shikhandi',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [],
    tags: ['panchala'],
    effects: [],
    flavor: 'Amba reborn, before whom Bhishma would not raise his bow.',
  },
  {
    id: 'drupada',
    name: 'Drupada',
    house: 'pandava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 7,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'panchala', amount: 1 }],
    tags: ['panchala'],
    effects: [],
    flavor: 'The king whose broken friendship lit the whole war.',
  },
  {
    id: 'yudhamanyu',
    name: 'Yudhamanyu',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'wheel-guard', amount: 2 }],
    tags: ['panchala', 'wheel-guard'],
    effects: [],
    flavor: 'One of the two who guarded Arjuna’s wheels to the last.',
  },
  {
    id: 'uttamaujas',
    name: 'Uttamaujas',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'wheel-guard', amount: 2 }],
    tags: ['panchala', 'wheel-guard'],
    effects: [],
    flavor: 'The other guardian of Arjuna’s chariot-wheels.',
  },

  // ---- Matsya (Virata's house) ----
  {
    id: 'virata',
    name: 'Virata',
    house: 'pandava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 7,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'matsya', amount: 1 }],
    tags: ['matsya'],
    effects: [],
    flavor: 'The king who hid the Pandavas, then died for them.',
  },
  {
    id: 'sweta',
    name: 'Sweta',
    house: 'pandava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 8,
    rows: ['ratha'],
    keywords: [],
    tags: ['matsya'],
    effects: [{ on: 'onPlay', target: { pick: 'highestEnemyUnit' }, actions: [{ kind: 'damage', amount: 3 }] }],
    flavor: 'Virata’s eldest, who raged through the van and fell on the first day.',
  },
  {
    id: 'sankha',
    name: 'Sankha',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 6,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'matsya', amount: 1 }],
    tags: ['matsya'],
    effects: [],
    flavor: 'Second of Virata’s fallen sons.',
  },
  {
    id: 'uttara',
    name: 'Uttara',
    house: 'pandava',
    type: 'unit',
    tier: 'rathi',
    basePower: 4,
    rows: ['ratha'],
    keywords: [{ kind: 'bond', tag: 'matsya', amount: 1 }],
    tags: ['matsya'],
    effects: [],
    flavor: 'The boy prince who found his courage behind Brihannala.',
  },

  // ---- Yadava, Chedi, Kekaya, and allied kings ----
  {
    id: 'satyaki',
    name: 'Satyaki',
    house: 'pandava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 8,
    rows: ['ratha'],
    keywords: [],
    tags: ['vrishni'],
    knownAstras: ['brahmastra'],
    effects: [],
    flavor: 'Arjuna’s disciple, the one Vrishni who chose the right side.',
  },
  {
    id: 'chekitana',
    name: 'Chekitana',
    house: 'pandava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 7,
    rows: ['ratha'],
    keywords: [],
    tags: ['vrishni'],
    effects: [],
    flavor: 'A Vrishni lord, commander of a Pandava division.',
  },
  {
    id: 'dhrishtaketu',
    name: 'Dhrishtaketu',
    house: 'pandava',
    type: 'unit',
    tier: 'maharathi',
    basePower: 7,
    rows: ['ratha'],
    keywords: [],
    tags: ['chedi'],
    effects: [],
    flavor: 'Shishupala’s son, who fought beside his father’s killer.',
  },
  {
    id: 'kekaya_brothers',
    name: 'The Kekaya Brothers',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 6,
    rows: ['ratha'],
    keywords: [],
    tags: ['kekaya'],
    effects: [],
    flavor: 'Five brothers of Kekaya, kin against kin.',
  },
  {
    id: 'kuntibhoja',
    name: 'Kuntibhoja',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 6,
    rows: ['ratha'],
    keywords: [],
    effects: [],
    flavor: 'The house that raised Kunti, come to fight for her sons.',
  },
  {
    id: 'yuyutsu',
    name: 'Yuyutsu',
    house: 'pandava',
    type: 'unit',
    tier: 'atirathi',
    basePower: 5,
    rows: ['ratha'],
    keywords: [{ kind: 'deathless' }],
    effects: [],
    flavor: 'The brother who changed sides before the conch, and lived.',
  },

  // ---- Levy ----
  {
    id: 'pandava_infantry',
    name: 'Pandava Footmen',
    house: 'pandava',
    type: 'unit',
    tier: 'rathi',
    basePower: 2,
    rows: ['padati'],
    keywords: [],
    effects: [],
    flavor: 'The uncounted spears of the Panchala levy.',
  },
];
